qe_portal/qe_portal/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from django.views.i18n import JavaScriptCatalog

from automation.views import Dashboard

from automation.views import CaseNew
from automation.views import CaseEdit
from automation.views import CaseDelete
from automation.views import CaseHistory

from automation.views import SuiteNew
from automation.views import SuiteEdit
from automation.views import SuiteDelete
from automation.views import SuiteHistory

from automation.views import SchedulerNew
from automation.views import SchedulerEdit
from automation.views import SchedulerDelete
from automation.views import SchedulerHistory

from automation.views import CaseList
from automation.views import SuiteList
from automation.views import SchedulerList
from automation.views import RunList
from automation.views import DetailList
from automation.views import TestRunSuite
from automation.views import Requirement
from automation.views import TaskMonitor

urlpatterns = [
    url(r'^admin/jsi18n', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^admin/', admin.site.urls),
    url(r'^test/', TestRunSuite),
    url(r'^dashboard/$', Dashboard.as_view()),
    url(r'^dashboard/case_new$', CaseNew.as_view(), name="case_new"),
    url(r'^dashboard/case_edit/(?P<id>[0-9]+)/$', CaseEdit.as_view(), name="case_edit"),
    url(r'^dashboard/case_delete/$', CaseDelete.as_view(), name="case_delete"),
    url(r'^dashboard/case_history/$', CaseHistory.as_view(), name="case_history"),

    url(r'^dashboard/suite_new$', SuiteNew.as_view(), name="suite_new"),
    url(r'^dashboard/suite_edit/(?P<id>[0-9]+)/$', SuiteEdit.as_view(), name="suite_edit"),
    url(r'^dashboard/suite_delete/$', SuiteDelete.as_view(), name="suite_delete"),
    url(r'^dashboard/suite_history/$', SuiteHistory.as_view(), name="suite_history"),

    url(r'^dashboard/scheduler_new$', SchedulerNew.as_view(), name="scheduler_new"),
    url(r'^dashboard/scheduler_edit/(?P<id>[0-9]+)/$', SchedulerEdit.as_view(), name="scheduler_edit"),
    url(r'^dashboard/scheduler_delete/$', SchedulerDelete.as_view(), name="scheduler_delete"),
    url(r'^dashboard/scheduler_history/$', SchedulerHistory.as_view(), name="scheduler_history"),

    url(r'^dashboard/case_list$', CaseList.as_view(), name="case_list"),
    url(r'^dashboard/suite_list$', SuiteList.as_view(), name="suite_list"),
    url(r'^dashboard/scheduler_list$', SchedulerList.as_view(), name="scheduler_list"),
    url(r'^dashboard/run_list$', RunList.as_view(), name="run_list"),
    url(r'^dashboard/detail_list$', DetailList.as_view(), name="detail_list"),

    url(r'^dashboard/task_monitor$', TaskMonitor.as_view(), name="task_monitor"),

    url(r'^markdownx/', include('markdownx.urls')),

    url(r'^requirement/requirement$', Requirement.as_view(), name="requirement"),
]

qe_portal/automation/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django import utils
from django.core.validators import MaxValueValidator, MinValueValidator
from simple_history.models import HistoricalRecords

from markdownx.models import MarkdownxField

import datetime

# Create your models here.


class CaseModel(models.Model):
    TYPE_CHOICES = (
        ('web', 'TC_WEB'),
        ('ios', 'TC_IOS'),
        ('android', 'TC_ANDROID'),
        ('es', 'TC_EMBEDDED'),
        ('vision', 'TC_VISION'),
        ('fc', 'TC_FC'),
    )

    PLATFORM_CHOICES = (
        ('win', 'WIN'),
        ('mac', 'MAC'),
        ('linux', 'LNX'),
    )

    type = models.CharField(max_length=16, null=False, choices=TYPE_CHOICES)
    name = models.CharField(max_length=128, null=False)
    description = models.TextField(default="", max_length=512, null=True, blank=True)
    cmd = models.CharField(max_length=32)
    params = models.CharField(max_length=128, null=True, blank=True)
    script = models.CharField(max_length=256)
    platform = models.CharField(max_length=32, choices=PLATFORM_CHOICES )
    timeout = models.IntegerField(default=120)

    history = HistoricalRecords()

    def __unicode__(self):
        return self.name + " : " + self.type + " : " + self.description


class SuiteModel(models.Model):
    name = models.CharField(default="", max_length=128, null=False, blank=False)
    description = models.TextField(default="", max_length=512, null=True, blank=True)
    create_time = datetime.datetime.now()
    emails = models.CharField(max_length=256, null=True, blank=True)
    cases = models.ManyToManyField(CaseModel)

    history = HistoricalRecords()

    def __unicode__(self):
        return unicode(self.name + self.description) or u''


class SchedulerModel(models.Model):
    name = models.CharField(max_length=128, null=False)
    description = models.TextField(default="", max_length=512, null=True, blank=True)
    suite = models.ForeignKey(SuiteModel)
    SCHED_TYPE = (
        ('ManualRun', 'Run Manually!'),
        ('RepeatEveryDay', 'Every Day!'),
        ('RepeatWorkingDay', 'Every WorkingDay!'),
        ('Reserved', 'Reserved'),
    )
    type = models.CharField(max_length=16, choices=SCHED_TYPE,)
    create_time = models.DateTimeField(default=utils.timezone.now, null=True, blank=True)
    # create_time = models.DateTimeField(default=datetime.datetime.now(), null=True, blank=True)
    emails = models.CharField(max_length=256, null=True, blank=True)
    appoint_at = models.TimeField(default=utils.timezone.now, null=True, blank=True)
    start_day = models.DateField(default=utils.timezone.now, null=True, blank=True)
    end_day = models.DateField(default=utils.timezone.now, null=True, blank=True)
    # appoint_at = models.TimeField(default=datetime.datetime.now(), null=True, blank=True)
    # start_day = models.DateField(default=datetime.datetime.now(), null=True, blank=True)
    # end_day = models.DateField(default=datetime.datetime.now(), null=True, blank=True)
    status = models.BooleanField(default=True)

    history = HistoricalRecords()

    def __unicode__(self):
        return self.name + ":" + self.type + ":" + self.description


class CaseRunningModel(models.Model):
    case = models.ForeignKey(CaseModel)
    start_time = models.DateTimeField(null=True, blank=True)
    end_time = models.DateTimeField(null=True, blank=True)
    run_time = models.IntegerField(default=0, validators=[MinValueValidator(0),], null=True, blank=True)
    ret_code = models.IntegerField(default=1, )
    error_msg = models.CharField(max_length=128, null=True, blank=True)
    log = models.CharField(max_length=128, null=True, blank=True)
    task_id = models.CharField(max_length=48, null=True, blank=True)

    def __unicode__(self):
        return "CaseRun:%s:%s:%s" % (self.pk, self.case.name, self.start_time)


class SuiteRunningModel(models.Model):
    suite = models.ForeignKey(SuiteModel)
    schedule = models.ForeignKey(SchedulerModel, default=5)
    case_runnings = models.ManyToManyField(CaseRunningModel)

    start_time = models.DateTimeField(null=True, blank=True)
    end_time = models.DateTimeField(null=True, blank=True)
    run_time = models.IntegerField(default=0, validators=[MinValueValidator(0),], null=True, blank=True)
    ret = models.IntegerField(default=1, blank=True, null=True)
    error_msg = models.CharField(max_length=256, null=True, blank=True)
    STATUS_TYPE = (
        ('Pending', 'Pending'),
        ('Running', 'Running'),
        ('Scheduled', 'Scheduled'),
        ('Completed','Completed'),
    )
    status = models.CharField(max_length=16, choices=STATUS_TYPE, default='Pending')
    progress = models.IntegerField(default=0, validators=[MaxValueValidator(100), MinValueValidator(0)])

    def __unicode__(self):
        return "SuiteRun:" + self.pk + ":" + self.suite.name + ":" + self.start_time


class RequirementModel(models.Model):
    Requirement = MarkdownxField()

qe_portal/automation/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import json
import subprocess
import os

from django.core.exceptions import ObjectDoesNotExist
from django.views import View
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.forms import modelform_factory
from django.shortcuts import get_object_or_404
from django.core import serializers
from django.conf import settings

from celery.result import AsyncResult
from qe_portal.celery import app

# Create your tests here.
from test_suites import Suite
from test_cases import Case

from automation.forms import CaseForm
from automation.forms import SuiteForm
from automation.forms import SchedulerForm

from automation.models import CaseModel
from automation.models import SuiteModel
from automation.models import SchedulerModel

from automation.models import SuiteRunningModel

from automation.schedulers import SchedulerAtOnce

from automation.models import RequirementModel
from automation.forms import RequirementForm


# Create your views here.


class Dashboard(View):
    def get(self, request):
        return render(request, 'dashboard/dashboard.html')

    def post(self, request):
        return render(request, 'dashboard/dashboard.html')


class CaseNew(View):
    def get(self, request):
        form = CaseForm()
        return render(request, 'dashboard/case_new.html', {'form': form})

    def post(self, request):
        form = CaseForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            new_case = form.save(commit=False)
            print new_case
            new_case.save()

            # process the data in form.cleaned_data as required
            # ...

#        subject = form.cleaned_data['subject']
#        message = form.cleaned_data['message']
#        sender = form.cleaned_data['sender']
#        cc_myself = form.cleaned_data['cc_myself']
#        recipients = ['info@example.com']
#        #send_mail(subject, message, sender, recipients)
#        return HttpResponseRedirect('/thanks/')
#
        #form = CaseForm()
        form = modelform_factory(CaseModel, fields='__all__')
        return render(request, 'dashboard/case_new.html', {'form': form})

class CaseEdit(View):

    def get(self, request, id):
        if id > 0:
            case = CaseModel.objects.get(pk=id)
            print case
            form = CaseForm(instance=case)
            print form
            return render(request,'dashboard/case_edit.html', {'form': form, 'id': id})
        else:
            return HttpResponse("Edit Case Error, Wrong ID Return!")


    def post(self, request, id):
        if id > 0:
            print request.POST
            print id
            print "post:update case id:", id
            instance = get_object_or_404(CaseModel, id=id)
            form = CaseForm(request.POST or None, instance=instance)
            if form.is_valid():
                form.save()
            return render(request, 'dashboard/case_edit.html', {'form': form, 'id':id})
        else:
            return HttpResponse("Update Case Error! Wrong Case ID!")

class CaseDelete(View):

    def get(self, request):
        data = {'id': id, 'ret': False}
        return HttpResponse(json.dumps(data), content_type='application/json')

    def post(self, request):
        if 'id' in request.POST:
            id = request.POST['id']
            if id > 0:
                instance = CaseModel.objects.get(id=id)
                instance.delete()
                print "Post, Case Deleted:", id
                data = {'id': id, 'ret': True}
                return HttpResponse(json.dumps(data), content_type='application/json')
        else:
            data = {'id': id, 'ret': False}
            return HttpResponse(json.dumps(data), content_type='application/json')

class CaseHistory(View):

    def get(self, request):
        data = {'id': id, 'h_list': []}
        return HttpResponse(json.dumps(data), content_type='application/json')

    def post(self, request):
        if 'id' in request.POST:
            id = request.POST['id']
            if id > 0:
                instance = CaseModel.objects.get(id=id)
                h_list = instance.history.all()
                print "Get Case Deleted:", id
                h_list = serializers.serialize('json', h_list)
                h_list_dict = json.loads(h_list)
                print h_list_dict
                data = dict({'id': id}.items() + {'h_list': h_list_dict}.items())
                return HttpResponse(json.dumps(data), content_type='application/json')
        else:
            data = {'id': id, 'h_list': []}
            return HttpResponse(json.dumps(data), content_type='application/json')


class SuiteNew(View):
    def get(self, request):
        form = SuiteForm()
        return render(request, 'dashboard/suite_new.html', {'form': form})

    def post(self, request):
        form = SuiteForm(request.POST)
        if form.is_valid():
            new_suite = form.save(commit=True)
            print "suite case number:", new_suite.cases.count()
        form = modelform_factory(SuiteModel, fields= '__all__')
        return render(request, 'dashboard/suite_new.html', {'form': form})


class SuiteEdit(View):

    def get(self, request, id):
        if id > 0:
            suite = SuiteModel.objects.get(pk=id)
            print suite
            form = SuiteForm(instance=suite)
            print form
            return render(request, 'dashboard/suite_edit.html', {'form': form, 'id': id})
        else:
            return HttpResponse("Edit Suite Error, Wrong ID Return!")


    def post(self, request, id):
        if id > 0:
            print request.POST
            print id
            print "post:update case id:", id
            instance = get_object_or_404(SuiteModel, id=id)
            form = SuiteForm(request.POST or None, instance=instance)
            if form.is_valid():
                form.save()
            return render(request, 'dashboard/suite_edit.html', {'form': form, 'id': id})
        else:
            return HttpResponse("Update Suite Error! Wrong ID!")


class SuiteDelete(View):

    def get(self, request):
        data = {'id': id, 'ret': False}
        return HttpResponse(json.dumps(data), content_type='application/json')

    def post(self, request):
        if 'id' in request.POST:
            id = request.POST['id']
            if id > 0:
                instance = SuiteModel.objects.get(id=id)
                instance.delete()
                print "Post, Case Deleted:", id
                data = {'id': id, 'ret': True}
                return HttpResponse(json.dumps(data), content_type='application/json')
        else:
            data = {'id': id, 'ret': False}
            return HttpResponse(json.dumps(data), content_type='application/json')


class SuiteHistory(View):

    def get(self, request):
        data = {'id': id, 'h_list': []}
        return HttpResponse(json.dumps(data), content_type='application/json')

    def post(self, request):
        if 'id' in request.POST:
            id = request.POST['id']
            if id > 0:
                instance = SuiteModel.objects.get(id=id)
                h_list = instance.history.all()
                print "Get Case Deleted:", id
                h_list = serializers.serialize('json', h_list)
                h_list_dict = json.loads(h_list)
                print h_list_dict
                data = dict({'id': id}.items() + {'h_list': h_list_dict}.items())
                return HttpResponse(json.dumps(data), content_type='application/json')
        else:
            data = {'id': id, 'h_list': []}
            return HttpResponse(json.dumps(data), content_type='application/json')


class SchedulerNew(View):
    def get(self, request):
        form = SchedulerForm()
        return render(request, 'dashboard/scheduler_new.html', {'form': form})

    def post(self, request):
        form = SchedulerForm(request.POST)
        if form.is_valid():
            new_model = form.save(commit=False)
            print new_model
            new_model.save()
        form = modelform_factory(SchedulerModel, exclude=["create_time", ])
        return render(request, 'dashboard/scheduler_new.html', {'form': form})

class SchedulerEdit(View):

    def get(self, request, id):
        if id > 0:
            model = SchedulerModel.objects.get(pk=id)
            print model
            form = SchedulerForm(instance=model)
            print form
            return render(request, 'dashboard/scheduler_edit.html', {'form': form, 'id': id})
        else:
            return HttpResponse("Edit Scheduler Error, Wrong ID Return!")


    def post(self, request, id):
        if id > 0:
            print request.POST
            print id
            print "post:update case id:", id
            instance = get_object_or_404(SchedulerModel, id=id)
            form = SchedulerForm(request.POST or None, instance=instance)
            if form.is_valid():
                form.save()
            return render(request, 'dashboard/scheduler_edit.html', {'form': form, 'id': id})
        else:
            return HttpResponse("Update Scheduler Error! Wrong ID!")


class SchedulerDelete(View):

    def get(self, request):
        data = {'id': id, 'ret': False}
        return HttpResponse(json.dumps(data), content_type='application/json')

    def post(self, request):
        if 'id' in request.POST:
            id = request.POST['id']
            if id > 0:
                instance = SchedulerModel.objects.get(id=id)
                instance.delete()
                print "Post, Scheduler Deleted:", id
                data = {'id': id, 'ret': True}
                return HttpResponse(json.dumps(data), content_type='application/json')
        else:
            data = {'id': id, 'ret': False}
            return HttpResponse(json.dumps(data), content_type='application/json')

qe_portal/automation/templates/dashboard/case_edit.html
{% extends 'dashboard/frame.html' %}

{% block main_content %}

    <h1>Case Edit</h1>
    <form method="POST" class="post-form"  method="post" action="{% url 'case_edit' id %}">{% csrf_token %}
         <div class="table-responsive">
             {% for field in form %}
                <div class="fieldWrapper">
                <fieldset class="module aligned ">
                    <div class="form-row field-type">
                        {{ field.errors }}
                        {{ field.label_tag }} {{ field }}
                        {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                        {% endif %}
                    </div>
                </fieldset>
                </div>
             {% endfor %}
        </div>
        <input type="submit" value="Submit" />
    </form>
{% endblock %}

qe_portal/automation/templates/dashboard/case_new.html
{% extends 'dashboard/frame.html' %}

{% block main_content %}
   <h1>Case New</h1>
    <form method="POST" class="post-form" action="case_new">{% csrf_token %}
         <div class="table-responsive">
             {% for field in form %}
                <div class="fieldWrapper">
                <fieldset class="module aligned ">
                    <div class="form-row field-type">
                        {{ field.errors }}
                        {{ field.label_tag }} {{ field }}
                        {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                        {% endif %}
                    </div>
                </fieldset>
                </div>
             {% endfor %}
        </div>
        <input type="submit" value="Submit" />
    </form>
{% endblock %}

qe_portal/automation/templates/dashboard/case_run_list.html
{% extends 'dashboard/frame.html' %}

{% block main_content %}
    <h1>Run List</h1>
    <form method="POST" class="post-form">{% csrf_token %}
         <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Case</th>
                  <th>Suite</th>
                  <th>Run Time</th>
                  <th>Return Code</th>
                  <th>Error Message</th>
                  <th>Task ID</th>
                </tr>
              </thead>
              <tbody>
              {% for run in runs %}
                <tr>
                  <td>{{ run.pk }}</td>
                  <td>{{ run.case.name }}</td>
                  <td>{{ run.suite.name }} </td>
                  <td>{{ run.run_time }}</td>
                  <td>
                      {% if run.ret_code %}
                      <span class="case_run_ret">
                          <img src="/static/dashboard/images/32x32/failed.png" alt="failed" style="width:18px;height:18px;border:0;">
                      </span>
                      {% else %}
                      <span class="case_run_ret">
                          <img src="/static/dashboard/images/32x32/success.png" alt="successful" style="width:18px;height:18px;border:0;">
                      </span>
                      {% endif %}
                  </td>
                  <td>{{ run.error_msg }} </td>
                  <td>{{ run.task_id }} </td>
                </tr>
              {% endfor %}
             </tbody>
            </table>
         </div>
    </form>
{% endblock %}

qe_portal/automation/templates/dashboard/casenew-3.html
<!DOCTYPE html>

<html lang="en-us" >
<head>
<title>Change scheduler model | Django site admin</title>
<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css" />
<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />


<script type="text/javascript" src="/admin/jsi18n/"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>
<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.js"></script>
<script type="text/javascript" src="/static/admin/js/urlify.js"></script>
<script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
<script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
<script type="text/javascript" src="/static/admin/js/calendar.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/DateTimeShortcuts.js"></script>

<meta name="robots" content="NONE,NOARCHIVE" />
</head>


<body class=" app-automation model-schedulermodel change-form"
  data-admin-utc-offset="0">

<!-- Container -->
<div id="container">

    
    <!-- Header -->
    <div id="header">
        <div id="branding">
        
<h1 id="site-name"><a href="/admin/">Django administration</a></h1>

        </div>
        
        
        <div id="user-tools">
            
                Welcome,
                <strong>admin</strong>.
            
            
                
                    <a href="/">View site</a> /
                
                
                    
                    
                
                
                <a href="/admin/password_change/">Change password</a> /
                
                <a href="/admin/logout/">Log out</a>
            
        </div>
        
        
        
    </div>
    <!-- END Header -->
    
<div class="breadcrumbs">
<a href="/admin/">Home</a>
&rsaquo; <a href="/admin/automation/">Automation</a>
&rsaquo; <a href="/admin/automation/schedulermodel/">Scheduler models</a>
&rsaquo; Scheduler:Scheduler_1:Now
</div>

    

    
        
    

    <!-- Content -->
    <div id="content" class="colM">
        
        <h1>Change scheduler model</h1>
        <div id="content-main">


  <ul class="object-tools">
    
    <li>
        
        <a href="/admin/automation/schedulermodel/5/history/" class="historylink">History</a>
    </li>
    
    
  </ul>


<form enctype="multipart/form-data" action="" method="post" id="schedulermodel_form" novalidate><input type='hidden' name='csrfmiddlewaretoken' value='uonLZyglWRgisI7WDIGzP1LErXT1u5N6ky9U8Rqpmu7CRMWkn69LYjzz9WiLrFhy' />
<div>







  <fieldset class="module aligned ">
    
    
    
        <div class="form-row field-suite">
            
            
                <div>
                    
                    
                        <label class="required" for="id_suite">Suite:</label>
                        
                            <div class="related-widget-wrapper">
    <select name="suite" required id="id_suite">
  <option value="">---------</option>

  <option value="1" selected>Test Suite:WebSuite_1</option>

</select>
    
        <a class="related-widget-wrapper-link change-related" id="change_id_suite"
            data-href-template="/admin/automation/suitemodel/__fk__/change/?_to_field=id&amp;_popup=1"
            title="Change selected suite model"><img src="/static/admin/img/icon-changelink.svg" alt="Change"/></a><a class="related-widget-wrapper-link add-related" id="add_id_suite"
            href="/admin/automation/suitemodel/add/?_to_field=id&amp;_popup=1"
            title="Add another suite model"><img src="/static/admin/img/icon-addlink.svg" alt="Add"/></a>
    
</div>
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-name">
            
            
                <div>
                    
                    
                        <label class="required" for="id_name">Name:</label>
                        
                            <input type="text" name="name" value="Scheduler_1" id="id_name" required class="vTextField" maxlength="128" />
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-type">
            
            
                <div>
                    
                    
                        <label class="required" for="id_type">Type:</label>
                        
                            <select name="type" required id="id_type">
  <option value="">---------</option>

  <option value="Now" selected>Run Now!</option>

  <option value="Repeat">Every Day!</option>

  <option value="Reserved">Reserved</option>

</select>
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-emails">
            
            
                <div>
                    
                    
                        <label for="id_emails">Emails:</label>
                        
                            <input type="text" name="emails" value="libaichao@zerozero.cn" id="id_emails" class="vTextField" maxlength="256" />
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-start_time">
            
            
                <div>
                    
                    
                        <label for="id_start_time">Start time:</label>
                        
                            <input type="text" name="start_time" id="id_start_time" class="vDateField" size="10" />
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-end_time">
            
            
                <div>
                    
                    
                        <label for="id_end_time">End time:</label>
                        
                            <input type="text" name="end_time" value="2017-07-22" id="id_end_time" class="vDateField" size="10" />
                        
                    
                    
                </div>
            
        </div>
    
</fieldset>













<div class="submit-row">
<input type="submit" value="Save" class="default" name="_save" />

    
    <p class="deletelink-box"><a href="/admin/automation/schedulermodel/5/delete/" class="deletelink">Delete</a></p>


<input type="submit" value="Save and add another" name="_addanother" />
<input type="submit" value="Save and continue editing" name="_continue" />
</div>



    <script type="text/javascript"
            id="django-admin-form-add-constants"
            src="/static/admin/js/change_form.js"
            >
    </script>




<script type="text/javascript"
        id="django-admin-prepopulated-fields-constants"
        src="/static/admin/js/prepopulate_init.js"
        data-prepopulated-fields="[]">
</script>


</div>
</form></div>

        
        <br class="clear" />
    </div>
    <!-- END Content -->

    <div id="footer"></div>
</div>
<!-- END Container -->

</body>
</html>

qe_portal/automation/templates/dashboard/dashboard.html
{% extends 'dashboard/frame.html' %}

{% block main_content %}
    <h1>New Test Case</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

qe_portal/automation/templates/dashboard/scheduler_edit.html
{% extends 'dashboard/frame.html' %}

{% block main_content %}
{% load static %}

<h1>Scheduler Edit</h1>
    <form method="POST" class="post-form" action="{% url 'scheduler_edit' id %}">{% csrf_token %}
         <div class="table-responsive">
             {% for field in form %}
                <div class="fieldWrapper">
                <fieldset class="module aligned ">
                    <div class="form-row field-type">
                        {{ field.errors }}
                        {{ field.label_tag }} {{ field }}
                        {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                        {% endif %}
                    </div>
                </fieldset>
                </div>
             {% endfor %}
         </div>
        <input type="submit" value="Submit" />
    </form>
{% endblock %}

qe_portal/automation/templates/dashboard/scheduler_new.html
{% extends 'dashboard/frame.html' %}

{% block main_content %}
{% load static %}

<h1>Scheduler New</h1>
    <form method="POST" class="post-form" action="scheduler_new">{% csrf_token %}
         <div class="table-responsive">
             {% for field in form %}
                <div class="fieldWrapper">
                <fieldset class="module aligned ">
                    <div class="form-row field-type">
                        {{ field.errors }}
                        {{ field.label_tag }} {{ field }}
                        {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                        {% endif %}
                    </div>
                </fieldset>
                </div>
             {% endfor %}
         </div>
        <input type="submit" value="Submit" />
    </form>
{% endblock %}